/*
 * This Scala source file was auto generated by running 'gradle buildInit --type scala-library'
 * by 'kuro' at '14/12/27 13:40' with Gradle 2.2.1
 *
 * @author kuro, @date 14/12/27 13:40
 */
class Library {
  def someLibraryMethod(): Boolean = true
}
