/*
 * This Scala Testsuite was auto generated by running 'gradle init --type scala-library'
 * by 'kuro' at '14/12/27 13:40' with Gradle 2.2.1
 *
 * @author kuro, @date 14/12/27 13:40
 */

import org.scalatest.FunSuite
import org.junit.runner.RunWith
import org.scalatest.junit.JUnitRunner

@RunWith(classOf[JUnitRunner])
class LibrarySuite extends FunSuite {
  test("someLibraryMethod is always true") {
    def library = new Library()
    assert(library.someLibraryMethod)
  }
}
